packages:
  # Include all of the core configuration
  core: !include alarm-clock-esp32-s3-jc3248w535c.yaml

esphome:
  project:
    name: "mathisloge.daylight-alarm-clock"
    version: dev # This will be replaced by the github workflows with the `release` version

dashboard_import:
  package_import_url: github://mathisloge/daylight-alarm-clock/alarm-clock-esp32-s3-jc3248w535c.yaml@main

esp32_improv:
  authorizer: none
improv_serial:

substitutions:
  name: "daylight-alarm-clock"
  friendly_name: "Daylight alarm clock"
  home_page: home_screen
  background_color: "0x374E58"
  border_color: "0x6a7a81"
  primary_color: "0x2ec0ff"
  text_sm: "16"
  text_md: "20"
  text_lg: "24"
  text_xl: "64"
  icons_sm: "20"
  icons_md: "26"
  icons_lg: "34"
